[program:hds-mqtt]
command=php /var/www/hds/artisan fras:mqtt-listen
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/hds-mqtt.log
stopwaitsecs=10
