[program:hds-queue]
command=php /var/www/hds/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/hds-queue.log
stopwaitsecs=10
