[program:hds-reverb]
command=php /var/www/hds/artisan reverb:start
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/hds-reverb.log
stopwaitsecs=10
